# Generated by Django 4.2 on 2023-04-15 22:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="\n            Designates whether this user should be treated as active.\n            Unselect this instead of deleting accounts.\n        ",
                        verbose_name="active or not",
                    ),
                ),
                (
                    "cover_photo_url",
                    models.URLField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
            },
        ),
        migrations.CreateModel(
            name="Photos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date time on which the object was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date time on which the object was last modified.",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="\n            Designates whether this user should be treated as active.\n            Unselect this instead of deleting accounts.\n        ",
                        verbose_name="active or not",
                    ),
                ),
                ("url", models.URLField(blank=True, default="", max_length=255)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), null=True, size=None
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="posts.posts",
                    ),
                ),
            ],
            options={
                "ordering": ["-created", "-modified"],
                "get_latest_by": "created",
            },
        ),
    ]
