# Generated by Django 4.2 on 2023-04-15 23:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="reviews",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(max_length=500), null=True, size=None
            ),
        ),
    ]
